- name: variables
  hosts: localhost
  vars_prompt:
  - name: "username"
    prompt: Please enter username
    private: false

  - name: "password" 
    prompt: Please enter password
    private: true   
  tasks:
  - name: Print Information
    ansible.builtin.debug:
      msg: "Hi, Username: {{username}}, Password: {{password}}"