- name: variables
  hosts: localhost

  tasks:
  - name: Print Information
    ansible.builtin.debug:
      msg: "Hi,I'm learning {{Course}} from trainer {{Trainer}}, duration is {{Duration}} and timings are {{Timinings}}"