- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: Print user info
    ansible.builtin.debug:
      msg: "Print user: {{ USER }}"  

  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc !=0  
      
  - name:
    ansible.builtin.debug:
      msg: "Hello"  