- name: filters
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{ Course | default('Ansible')}}"

- name: upper case
  hosts: localhost
  vars:
    yc: "hello, yojana"
  tasks:
  - name: Print uppercase
    ansible.builtin.debug:
      msg: "{{ yc | upper }}"

- name: lower case
  hosts: localhost
  vars:
    yc: "HII, CHIKRI"
  tasks:  
  - name: print lowercase
    ansible.builtin.debug:
      msg: "{{yc | lower}}"

- name: duplicates
  hosts: localhost
  vars:
   numbers: [1,3,5,8,7,3,5]
  tasks:  
  - name: print unique numbers and remove duplicates 
    ansible.builtin.debug:
      msg: "{{numbers | unique}}"      

- name: min and max
  hosts: localhost
  vars:
   numbers: [15,45,30,20,5,100,]
  tasks:  
  - name: print min and max 
    ansible.builtin.debug:
      msg: "{{The min is | min , and max: | max}}"            