- name: filters
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{ Course | default('Ansible')}}"

- name: upper case and lower case
  hosts: localhost
  vars:
    yc: "hello, yojana"
  tasks:
  - name: Print uppercase
    ansible.builtin.debug:
      msg: "{{ yc | upper }}"

  vars:
    yc: "HII, CHIKRI"
  - name: print lowercase
    ansible.builtin.debug:
      msg: "{{yc | lower}}