- name: loops
  hosts: localhost
  tasks:
  - name: print the tools 
    ansible.builtin.debug
      msg: "Hello, I'm {{ items }}}"
    loop: 
      - Shell
      - Ansible
      - Jenkins
      - Terraform
      - Docker