- name: Install the packages
  hosts: web
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: "{{ item.state}}"
    loop:
    - { name: 'mysql', state: 'latest' }
    - { name: 'nginx', state: 'absent' }
    - { name: 'postfix', state: 'absent' }